### ISSUE TITLE
EQB Home page text

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/eqb.colectica#1]
From: Mari Kleemola (TAU)
Date: Mon, 19 Jun 2023 at 09:33
Subject: RE: CESSDA European Question Bank
To: Bonnie Wolff-Boenisch, John Shepherdson
Cc: Vanja Komljenovic 

Hi Bonnie, All,

 <snip>

Since anyone can access EQB (and the URL is not that hard to guess), I think we should add some information about the status of the service in the EQB homepage above the browse section where there’s now just a title ‘Home’ (for an example of such info text, see FSD’s longitudinal portal: https://loda.fsd.tuni.fi/ and/or screenshot below). Adding a short text chapter is simple and quick for someone who has the admin rights (Matthew?).

The text could be something like:

**“The CESSDA Euro Question Bank (EQB) is a cross-national question bank that integrates and displays metadata from European surveys.

The platform allows the user to search, browse, compare and download survey questions and study-related metadata. Users can search question texts, response alternatives and keywords. The service is still in development state and contains currently metadata produced in the SSHOC project. Please contact support@cessda.eu for further information.”**

All the best,

Mari

**Comment by john-shepherdson** [comment]
![LODA Colectica home page](https://github.com/cessda/eqb.colectica/assets/107628491/d2d94ee2-5555-4f5c-a773-9b7066d7cdff)

**Comment by matthew-morris-cessda** [comment]
The text has been applied to the EQB home page without modification

![image](https://github.com/cessda/eqb.colectica/assets/68543725/fb362a38-d461-4da8-b85c-a578bdf06877)
